# Generated by Django 5.1.4 on 2024-12-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(default='default', null=True, upload_to='media'),
        ),
    ]
