# Generated by Django 5.1.4 on 2024-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(default='default', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
